### PR TITLE
Deploy script tweaks

### PR DESCRIPTION
**Pull request by nghi01**
* Fix bugs with running the modules from the command line
* Adjust deploy scripts to run the modules successfully
* Make some minor tweaks to tests to run without complaints
* Implement input file to deploy script
* Adding a contributing peer which is basically do all the things that commissioning peer (peer.py) do except commissioning art pieces

### CODE REVIEW

**Comment by nghi01** [comment]
/usr/lib/python3.10/asyncio/base_events.py:675: RuntimeWarning: coroutine 'Peer.send_deadline_reached' was never awaited
  self._scheduled.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
I think one of the reasons could be how I misunderstood how Alex coded the address
I was thinking about the argument address as merely 127.0.0.1, together with the port, they will be hosted on 127.0.0.1:50000 for example, but seemingly the network address Alex wants to input into as cmd arguments are the network address, not the peer address.
So there is definitely problem since the peer is hosted on 0.0.0.0:50000 instead of 127.0.0.1:50000

**Comment by nghi01** [comment]
On second though, might be just our code not meshing too well and needs some refactoring.

**Comment by zimmermatt** [comment]
Seems more likely the case. The `0.0.0.0` address would receive on the
`localhost` address (`127.0.0.1`), so I don't think that's the issue.

Remember from our networking overview, `0.0.0.0` means listen on any
configured interface on this host, which includes the `localhost` address.

**Comment by zimmermatt** [comment]
I have an appointment to play tennis late morning/early afternoon today, so I may not have time to look at this before our daily stand up. If you're confident in it once you've fixed what you called out and if this is blocking other integration work, you should have access rights to able to merge it yourself. Feel free to do so.

**Pull request merged**
